// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaE6RsHlMuNGeny65QFNpSFNhsZLnAUlo',
    appId: '1:86217792539:android:05cf885222508a13a8ecbe',
    messagingSenderId: '86217792539',
    projectId: 'finance-assistant-ac2ec',
    storageBucket: 'finance-assistant-ac2ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqGSsOH7sojvcm2o_euG59DsKQ0ROC9-Y',
    appId: '1:86217792539:ios:7a68ae44a3d1ceb6a8ecbe',
    messagingSenderId: '86217792539',
    projectId: 'finance-assistant-ac2ec',
    storageBucket: 'finance-assistant-ac2ec.firebasestorage.app',
    androidClientId: '86217792539-rdqko4nll68e498bk2ueq0au60f0al8j.apps.googleusercontent.com',
    iosClientId: '86217792539-mf7acfta809rki1ggvgetar5c7loeier.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeAssistent',
  );
}
